# reproducibility of [train]Pytorch Swin+5Fold+some tips
global:
  debug: false
  seed: 42
  device: cuda

amp: true

train:
  max_epoch: 5
  fold: 5
  shuffle: true

augmentation:
  train:
    SmallestMaxSize: {max_size: 224, p: 1.0}
    # Normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
    RandomCrop: {height: 224, width: 224, p: 1.0}
    VerticalFlip: {p: 0.5}
    HorizontalFlip: {p: 0.5}
    # ToTensor: {always_apply: True}
  valid:
    Resize: {height: 224, width: 224}
    # Normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
    # ToTensor: {always_apply: True}

dataset:
  name: ReproDataset

loader:
  train: {batch_size: 16, shuffle: True, num_workers: 2, pin_memory: True, drop_last: True}
  valid: {batch_size: 32, shuffle: False, num_workers: 2, pin_memory: True, drop_last: False}
model:
  name: Repro001
  params:
    model_name: swin_tiny_patch4_window7_224
    out_features: 1
    inp_channels: 3
    pretrained: True

optimizer:
  name: AdamW
  params:
    lr: 2.0e-5

loss: BCEWithLogitsLoss

scheduler:
  name: OneCycleLR
  params:
    pct_start: 0.25
    epochs: 5
    max_lr: 2.0e-5

accumulation: 1

fold_type: skf

metrics:
  - usr_rmse_score
